### ISSUE TITLE
private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by mvz** [mmozuras/pronto-rubocop#11]
This happens with Ruby 2.2.0, but not 2.1.5. Running just rubocop works fine in both versions:

```
[matijs@walnut] pronto run
/home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.29.1/lib/rubocop/config_loader.rb:117:in `load_yaml_configuration': private method `load' called for Psych:Module (NoMethodError)
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.29.1/lib/rubocop/config_loader.rb:27:in `load_file'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.29.1/lib/rubocop/config_loader.rb:85:in `configuration_from_file'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rubocop-0.29.1/lib/rubocop/config_store.rb:40:in `for'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-rubocop-0.4.1/lib/pronto/rubocop.rb:42:in `excluded?'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-rubocop-0.4.1/lib/pronto/rubocop.rb:17:in `block in run'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto/git/patches.rb:15:in `each'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto/git/patches.rb:15:in `each'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-rubocop-0.4.1/lib/pronto/rubocop.rb:14:in `select'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-rubocop-0.4.1/lib/pronto/rubocop.rb:14:in `run'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:60:in `block in run_all_runners'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `map'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:59:in `run_all_runners'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto.rb:34:in `run'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/lib/pronto/cli.rb:52:in `run'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/matijs/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/pronto-0.4.1/bin/pronto:6:in `<top (required)>'
	from /home/matijs/.rbenv/versions/2.2.0/bin/pronto:23:in `load'
	from /home/matijs/.rbenv/versions/2.2.0/bin/pronto:23:in `<main>'
```

**Comment by mmozuras** [comment]
@mvz more about this can issue can be found here:
https://github.com/bbatsov/rubocop/issues/1510#issuecomment-83545184

It appears to be fixed with ruby `2.2.1`. Can you try to reproduce?

**Comment by mmozuras** [comment]
@mvz any luck? :smile:

**Comment by mvz** [comment]
@mmozuras Sorry for the delay. I tried with 2.2.2 and it seems to be fixed.

**Comment by mmozuras** [comment]
@mvz no problem, thanks! :bow:
